BIN_LIB=PF2XLSX
LIBLIST=$(BIN_LIB)
SHELL=/QOpenSys/usr/bin/qsh

all: PF2XLSX.SQLRPGLE

%.SQLRPGLE:
    system -s "CHGATR OBJ(./QRPGLESRC/$*.SQLRPGLE) ATR(*CCSID) VALUE(1252)"
	liblist -a $(LIBLIST);\
	system "CRTSQLRPGI OBJ($(BIN_LIB/$*) SRCSTMF() COMMIT(*NONE) DBGVIEW(*SOURCE) OPTION(*EVENTF)"